name: Deploy to Encore Cloud

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Deploy to Encore Cloud
        run: npx encore deploy --yes
        env:
          ENCORE_API_KEY: ${{ secrets.ENCORE_API_KEY }}
